config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :clients do
    resources :accounts
  end

  resources :orders do
    post :accept, on: :member
    post :reject, on: :member
    post :accept_all, on: :collection
    post :reject_all, on: :collection
  end

  resources :activities
  resources :asset_classes
  resources :portfolios
  resources :securities

  get '/search/results', to: 'search#results'

  get 'dashboard/client_count', to: 'dashboard#client_count'
  get 'dashboard/account_count', to: 'dashboard#account_count'
  get 'dashboard/biggest_account', to: 'dashboard#biggest_account'
  get 'dashboard/aum', to: 'dashboard#aum'

  root 'dashboard#index'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :bigint           not null, primary key
#  client_id    :bigint
#  portfolio_id :bigint
#  canonical_id :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Account < ApplicationRecord
  include PgSearch::Model

  belongs_to :client
  belongs_to :portfolio
  has_many :positions
  has_many :securities, through: :positions

  multisearchable against: %i[name canonical_id]

  def self.biggest
    account = select('accounts.id, sum(positions.quantity * securities.value) as aum').joins(:positions).joins(:securities).group('accounts.id').order('aum desc').first
    { account: find(account.id), aum: account.aum}
  end
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :bigint           not null, primary key
#  account_id    :bigint
#  security_id   :bigint
#  activity_type :string
#  amount        :decimal(, )
#  posted_at     :datetime
#  effective_on  :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Activity < ApplicationRecord
  belongs_to :account
  belongs_to :security
end

app/models/allocation.rb
# == Schema Information
#
# Table name: allocations
#
#  id             :bigint           not null, primary key
#  portfolio_id   :bigint
#  asset_class_id :bigint
#  amount         :decimal(, )
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Allocation < ApplicationRecord
  belongs_to :portfolio
  belongs_to :asset_class
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/asset_class.rb
# == Schema Information
#
# Table name: asset_classes
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class AssetClass < ApplicationRecord
  include PgSearch::Model

  has_many :asset_class_securities
  has_many :securities, through: :asset_class_securities

  multisearchable against: :name
end

app/models/asset_class_security.rb
# == Schema Information
#
# Table name: asset_class_securities
#
#  id             :bigint           not null, primary key
#  asset_class_id :bigint
#  security_id    :bigint
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class AssetClassSecurity < ApplicationRecord
  belongs_to :asset_class
  belongs_to :security
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :bigint           not null, primary key
#  name       :string
#  address    :string
#  city       :string
#  postal     :string
#  province   :string
#  country    :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Client < ApplicationRecord
  include PgSearch::Model

  has_many :accounts

  multisearchable against: %i[name address city postal province country phone]
  pg_search_scope :search_by_all, against: %i[name address city postal province country phone]

  def self.cities
    distinct(:city).pluck(:city).sort
  end

  def self.countries
    distinct(:country).pluck(:country).sort
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :bigint           not null, primary key
#  account_id  :bigint
#  security_id :bigint
#  order_type  :string
#  amount      :decimal(, )
#  posted_at   :datetime
#  rejected_at :datetime
#  accepted_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'sidekiq/api'

class Order < ApplicationRecord
  belongs_to :account
  belongs_to :security

  def self.orders_in_process_count
    count = 0
    queue = Sidekiq::Queue.new('default')
    queue.each do |job|
      count += 1 if job.args.first['job_class'][/(OrderAcceptJob|OrderRejectJob)/]
    end
    count
  rescue
    0
  end
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Portfolio < ApplicationRecord
  include PgSearch::Model

  has_many :allocations
  has_many :accounts
  has_many :clients, through: :accounts

  multisearchable against: :name
  pg_search_scope :search_by_name, against: :name
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id          :bigint           not null, primary key
#  account_id  :bigint
#  security_id :bigint
#  quantity    :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Position < ApplicationRecord
  belongs_to :account
  belongs_to :security

  def self.aum
    data = select('sum(positions.quantity * securities.value) as aum').joins(:security)
    data.map(&:aum).first
  end

  def value
    quantity * security.value
  end
end

app/models/security.rb
# == Schema Information
#
# Table name: securities
#
#  id         :bigint           not null, primary key
#  symbol     :string
#  buy_cost   :decimal(, )
#  sell_cost  :decimal(, )
#  value      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Security < ApplicationRecord
  include PgSearch::Model

  has_many :positions
  has_many :asset_class_securities

  multisearchable against: :symbol
  pg_search_scope :search_by_symbol, against: :symbol
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def client_count
    @client_count = get_client_count
  end

  def account_count
    @account_count = get_account_count
  end

  def biggest_account
    @biggest_account = get_biggest_account
  end

  def aum
    @aum = get_aum
  end

  private

  def get_client_count
    Client.slowly.count
  end

  def get_account_count
    Account.slowly.count
  end

  def get_biggest_account
    Account.slowly.biggest
  end

  def get_aum
    Position.slowly.aum
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asset_classes_helper.rb
module AssetClassesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/dashboard/account_count.html.erb
<%= turbo_frame_tag 'dashboard-account-count' do %>
  <div class="box">
    <p class="subtitle is-5">Accounts</p>
    <p class="title is-2"><%= @account_count %></p>
  </div>
<% end %>

app/views/dashboard/aum.html.erb
<%= turbo_frame_tag 'dashboard-aum' do %>
  <div class="box">
    <p class="subtitle is-5">AUM</p>
    <p class="title is-1"><%= number_to_currency @aum %></p>
  </div>
<% end %>

app/views/dashboard/biggest_account.html.erb
<%= turbo_frame_tag 'dashboard-biggest-account' do %>
  <div class="box">
    <p class="subtitle is-5">Biggest Account</p>
    <p class="title is-3"><%= @biggest_account[:account].canonical_id %> (<%= @biggest_account[:account].name %>)</p>
    <p class="title is-2"><%= number_to_currency @biggest_account[:aum] %></p>
  </div>
<% end %>

app/views/dashboard/client_count.html.erb
<%= turbo_frame_tag 'dashboard-client-count' do %>
  <div class="box">
    <p class="subtitle is-5">Clients</p>
    <p class="title is-2"><%= @client_count %></p>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Dashboard</h1>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column">
        <%= turbo_frame_tag 'dashboard-aum', src: dashboard_aum_path do %>
          <div class="box">
            <p class="subtitle is-5">AUM</p>
            <p class="title is-1">-</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= turbo_frame_tag 'dashboard-client-count', src: dashboard_client_count_path do %>
          <div class="box">
            <p class="subtitle is-5">Clients</p>
            <p class="title is-2">-</p>
          </div>
        <% end %>
      </div>
      <div class="column">
        <%= turbo_frame_tag 'dashboard-account-count', src: dashboard_account_count_path do %>
          <div class="box">
            <p class="subtitle is-5">Accounts</p>
            <p class="title is-2">-</p>
          </div>
        <% end %>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <%= turbo_frame_tag 'dashboard-biggest-account', src: dashboard_biggest_account_path do %>
          <div class="box">
            <p class="subtitle is-5">Biggest Account</p>
            <p class="title is-3">-</p>
            <p class="title is-2">-</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>