config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :clients do
    resources :accounts
  end

  resources :orders do
    post :accept, on: :member
    post :reject, on: :member
    post :accept_all, on: :collection
    post :reject_all, on: :collection
  end

  resources :activities
  resources :asset_classes
  resources :portfolios
  resources :securities

  get '/search/results', to: 'search#results'

  get 'dashboard/client_count', to: 'dashboard#client_count'
  get 'dashboard/account_count', to: 'dashboard#account_count'
  get 'dashboard/biggest_account', to: 'dashboard#biggest_account'
  get 'dashboard/aum', to: 'dashboard#aum'

  root 'dashboard#index'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :bigint           not null, primary key
#  client_id    :bigint
#  portfolio_id :bigint
#  canonical_id :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Account < ApplicationRecord
  include PgSearch::Model

  belongs_to :client
  belongs_to :portfolio
  has_many :positions
  has_many :securities, through: :positions

  multisearchable against: %i[name canonical_id]

  def self.biggest
    account = select('accounts.id, sum(positions.quantity * securities.value) as aum').joins(:positions).joins(:securities).group('accounts.id').order('aum desc').first
    { account: find(account.id), aum: account.aum}
  end
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :bigint           not null, primary key
#  account_id    :bigint
#  security_id   :bigint
#  activity_type :string
#  amount        :decimal(, )
#  posted_at     :datetime
#  effective_on  :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Activity < ApplicationRecord
  belongs_to :account
  belongs_to :security
end

app/models/allocation.rb
# == Schema Information
#
# Table name: allocations
#
#  id             :bigint           not null, primary key
#  portfolio_id   :bigint
#  asset_class_id :bigint
#  amount         :decimal(, )
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Allocation < ApplicationRecord
  belongs_to :portfolio
  belongs_to :asset_class
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/asset_class.rb
# == Schema Information
#
# Table name: asset_classes
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class AssetClass < ApplicationRecord
  include PgSearch::Model

  has_many :asset_class_securities
  has_many :securities, through: :asset_class_securities

  multisearchable against: :name
end

app/models/asset_class_security.rb
# == Schema Information
#
# Table name: asset_class_securities
#
#  id             :bigint           not null, primary key
#  asset_class_id :bigint
#  security_id    :bigint
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class AssetClassSecurity < ApplicationRecord
  belongs_to :asset_class
  belongs_to :security
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :bigint           not null, primary key
#  name       :string
#  address    :string
#  city       :string
#  postal     :string
#  province   :string
#  country    :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Client < ApplicationRecord
  include PgSearch::Model

  has_many :accounts

  multisearchable against: %i[name address city postal province country phone]
  pg_search_scope :search_by_all, against: %i[name address city postal province country phone]

  def self.cities
    distinct(:city).pluck(:city).sort
  end

  def self.countries
    distinct(:country).pluck(:country).sort
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :bigint           not null, primary key
#  account_id  :bigint
#  security_id :bigint
#  order_type  :string
#  amount      :decimal(, )
#  posted_at   :datetime
#  rejected_at :datetime
#  accepted_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'sidekiq/api'

class Order < ApplicationRecord
  belongs_to :account
  belongs_to :security

  def self.orders_in_process_count
    count = 0
    queue = Sidekiq::Queue.new('default')
    queue.each do |job|
      count += 1 if job.args.first['job_class'][/(OrderAcceptJob|OrderRejectJob)/]
    end
    count
  rescue
    0
  end
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Portfolio < ApplicationRecord
  include PgSearch::Model

  has_many :allocations
  has_many :accounts
  has_many :clients, through: :accounts

  multisearchable against: :name
  pg_search_scope :search_by_name, against: :name
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id          :bigint           not null, primary key
#  account_id  :bigint
#  security_id :bigint
#  quantity    :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Position < ApplicationRecord
  belongs_to :account
  belongs_to :security

  def self.aum
    data = select('sum(positions.quantity * securities.value) as aum').joins(:security)
    data.map(&:aum).first
  end

  def value
    quantity * security.value
  end
end

app/models/security.rb
# == Schema Information
#
# Table name: securities
#
#  id         :bigint           not null, primary key
#  symbol     :string
#  buy_cost   :decimal(, )
#  sell_cost  :decimal(, )
#  value      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Security < ApplicationRecord
  include PgSearch::Model

  has_many :positions
  has_many :asset_class_securities

  multisearchable against: :symbol
  pg_search_scope :search_by_symbol, against: :symbol
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :load_orders, except: %i[accept reject]

  def index
    @orders = @orders.page(params[:page]).per(50)
  end

  def accept
    @order = Order.find(params[:id])
    @order.update(rejected_at: nil, accepted_at: Time.current)
  end

  def reject
    @order = Order.find(params[:id])
    @order.update(accepted_at: nil, rejected_at: Time.current)
  end

  def accept_all
    @orders.find_each do |order|
      OrderAcceptJob.perform_later order
    end

    render partial: 'bulk_order'
  end

  def reject_all
    @orders.find_each do |order|
      OrderRejectJob.perform_later order
    end

    render partial: 'bulk_order'
  end

  private

  def load_orders
    @orders = Order.order(posted_at: :desc).includes(:account, :security)
    @orders = @orders.where(accounts: { client_id: params[:client_id] }).joins(:account) if params[:client_id].present?
    @orders = @orders.where(account_id: params[:account_id]) if params[:account_id].present?
    @orders = @orders.where(security_id: params[:security_id]) if params[:security_id].present?
    @orders = @orders.where(order_type: params[:order_type]) if params[:order_type].present?
    @orders = @orders.where.not(rejected_at: nil) if params[:status] == 'Rejected'
    @orders = @orders.where.not(accepted_at: nil) if params[:status] == 'Accepted'
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @records = PgSearch.multisearch(params[:q]).page(params[:page]).per(5)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/asset_classes_helper.rb
module AssetClassesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/orders/_bulk_order.html.erb
<%= turbo_frame_tag 'bulk-order-action' do %>
  <% if Order.orders_in_process_count.zero? %>
    Processing complete!
  <% else %>
    Processing <%= pluralize(Order.orders_in_process_count, 'order') %>.
  <% end %>
<% end %>

app/views/orders/accept.html.erb
<%= turbo_frame_tag dom_id(@order) do %>
  <span class="has-text-success"><%= @order.accepted_at %></span>
<% end %>

app/views/orders/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">Orders</h1>
  </div>
</section>

<section class="section">
  <div class="container mb-4" data-controller="filter-toggle">
    <form class="is-hidden is-inline-block" data-turbo-frame="index-list" data-filter-toggle-target="form">
      <div class="field is-grouped is-grouped-multiline">
        <div class="control">
          <div class="select">
            <%= select_tag 'client_id', options_from_collection_for_select(Client.all.order(:name), 'id', 'name'), include_blank: 'Client' %>
          </div>
        </div>
        <div class="control">
          <div class="select">
            <%= select_tag 'account_id', options_from_collection_for_select(Account.all.order(:canonical_id), 'id', 'canonical_id'), include_blank: 'Account' %>
          </div>
        </div>
        <div class="control">
          <div class="select">
            <%= select_tag 'security_id', options_from_collection_for_select(Security.all.order(:symbol), 'id', 'symbol'), include_blank: 'Security' %>
          </div>
        </div>
        <div class="control">
          <div class="select">
            <%= select_tag 'order_type', options_for_select(Order.distinct(:order_type).pluck(:order_type).sort), include_blank: 'Type' %>
          </div>
        </div>
        <div class="control">
          <div class="select">
            <%= select_tag 'status', options_for_select(%w(Rejected Accepted)), include_blank: 'Status' %>
          </div>
        </div>
        <div class="control">
          <input class="button is-info" type="submit" value="Filter">
        </div>
      </div>
    </form>
    <button class="button is-inline-block" data-action="filter-toggle#toggle">&harr;</button>
  </div>
  <%= turbo_frame_tag 'index-list' do %>
    <div class="container">
      <div class="buttons is-pulled-right">
        <%= turbo_stream_from 'bulk-order-count' %>
        <%= turbo_frame_tag 'bulk-order-action' do %>
          <% if Order.orders_in_process_count.zero? %>
            <%= form_with url: accept_all_orders_path, class: 'is-inline-block mr-1' do |f| %>
              <%= hidden_field_tag 'account_id', params[:account_id] %>
              <%= hidden_field_tag 'security_id', params[:security_id] %>
              <%= hidden_field_tag 'order_type', params[:order_type] %>
              <%= hidden_field_tag 'status', params[:status] %>
              <%= f.submit "Accept All (#{@orders.total_count})", class: 'button is-success' %>
            <% end %>
            <%= form_with url: reject_all_orders_path, class: 'is-inline-block' do |f| %>
              <%= hidden_field_tag 'account_id', params[:account_id] %>
              <%= hidden_field_tag 'security_id', params[:security_id] %>
              <%= hidden_field_tag 'order_type', params[:order_type] %>
              <%= hidden_field_tag 'status', params[:status] %>
              <%= f.submit "Reject All (#{@orders.total_count})", class: 'button is-danger' %>
            <% end %>
          <% else %>
            <%= render partial: 'bulk_order' %>
          <% end %>
        <% end %>
      </div>
      <table class="table is-bordered is-fullwidth is-striped is-hoverable">
        <thead>
          <tr>
            <th>Account</th>
            <th>Security</th>
            <th>Type</th>
            <th>Amount</th>
            <th>Posted</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <th class="has-text-left"><%= order.account.canonical_id %></th>
              <td><%= order.security.symbol %></td>
              <td><%= order.order_type %></td>
              <% if order.order_type[/QUANTITY/] %>
                <td class="has-text-right"><%= order.amount %></td>
              <% else %>
                <td class="has-text-right"><%= number_to_currency order.amount %></td>
              <% end %>
              <td><%= order.posted_at %></td>
              <td>
                <%= turbo_frame_tag dom_id(order) do %>
                  <% if order.rejected_at %>
                    <span class="has-text-danger"><%= order.rejected_at %></span>
                  <% elsif order.accepted_at %>
                    <span class="has-text-success"><%= order.accepted_at %></span>
                  <% else %>
                    <%= form_with url: accept_order_path(order), class: 'is-inline mr-1' do |f| %>
                      <%= f.submit 'Accept', class: 'button is-success' %>
                    <% end %>
                    <%= form_with url: reject_order_path(order), class: 'is-inline' do |f| %>
                      <%= f.submit 'Reject', class: 'button is-danger' %>
                    <% end %>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @orders %>
    </div>
  <% end %>
</section>

app/views/orders/reject.html.erb
<%= turbo_frame_tag dom_id(@order) do %>
  <span class="has-text-danger"><%= @order.rejected_at %></span>
<% end %>