config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :clients do
    resources :accounts
  end

  resources :orders do
    post :accept, on: :member
    post :reject, on: :member
    post :accept_all, on: :collection
    post :reject_all, on: :collection
  end

  resources :activities
  resources :asset_classes
  resources :portfolios
  resources :securities

  get '/search/results', to: 'search#results'

  get 'dashboard/client_count', to: 'dashboard#client_count'
  get 'dashboard/account_count', to: 'dashboard#account_count'
  get 'dashboard/biggest_account', to: 'dashboard#biggest_account'
  get 'dashboard/aum', to: 'dashboard#aum'

  root 'dashboard#index'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :bigint           not null, primary key
#  client_id    :bigint
#  portfolio_id :bigint
#  canonical_id :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Account < ApplicationRecord
  include PgSearch::Model

  belongs_to :client
  belongs_to :portfolio
  has_many :positions
  has_many :securities, through: :positions

  multisearchable against: %i[name canonical_id]

  def self.biggest
    account = select('accounts.id, sum(positions.quantity * securities.value) as aum').joins(:positions).joins(:securities).group('accounts.id').order('aum desc').first
    { account: find(account.id), aum: account.aum}
  end
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :bigint           not null, primary key
#  account_id    :bigint
#  security_id   :bigint
#  activity_type :string
#  amount        :decimal(, )
#  posted_at     :datetime
#  effective_on  :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class Activity < ApplicationRecord
  belongs_to :account
  belongs_to :security
end

app/models/allocation.rb
# == Schema Information
#
# Table name: allocations
#
#  id             :bigint           not null, primary key
#  portfolio_id   :bigint
#  asset_class_id :bigint
#  amount         :decimal(, )
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Allocation < ApplicationRecord
  belongs_to :portfolio
  belongs_to :asset_class
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/asset_class.rb
# == Schema Information
#
# Table name: asset_classes
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class AssetClass < ApplicationRecord
  include PgSearch::Model

  has_many :asset_class_securities
  has_many :securities, through: :asset_class_securities

  multisearchable against: :name
end

app/models/asset_class_security.rb
# == Schema Information
#
# Table name: asset_class_securities
#
#  id             :bigint           not null, primary key
#  asset_class_id :bigint
#  security_id    :bigint
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class AssetClassSecurity < ApplicationRecord
  belongs_to :asset_class
  belongs_to :security
end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id         :bigint           not null, primary key
#  name       :string
#  address    :string
#  city       :string
#  postal     :string
#  province   :string
#  country    :string
#  phone      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Client < ApplicationRecord
  include PgSearch::Model

  has_many :accounts

  multisearchable against: %i[name address city postal province country phone]
  pg_search_scope :search_by_all, against: %i[name address city postal province country phone]

  def self.cities
    distinct(:city).pluck(:city).sort
  end

  def self.countries
    distinct(:country).pluck(:country).sort
  end
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :bigint           not null, primary key
#  account_id  :bigint
#  security_id :bigint
#  order_type  :string
#  amount      :decimal(, )
#  posted_at   :datetime
#  rejected_at :datetime
#  accepted_at :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'sidekiq/api'

class Order < ApplicationRecord
  belongs_to :account
  belongs_to :security

  def self.orders_in_process_count
    count = 0
    queue = Sidekiq::Queue.new('default')
    queue.each do |job|
      count += 1 if job.args.first['job_class'][/(OrderAcceptJob|OrderRejectJob)/]
    end
    count
  rescue
    0
  end
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Portfolio < ApplicationRecord
  include PgSearch::Model

  has_many :allocations
  has_many :accounts
  has_many :clients, through: :accounts

  multisearchable against: :name
  pg_search_scope :search_by_name, against: :name
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id          :bigint           not null, primary key
#  account_id  :bigint
#  security_id :bigint
#  quantity    :decimal(, )
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Position < ApplicationRecord
  belongs_to :account
  belongs_to :security

  def self.aum
    data = select('sum(positions.quantity * securities.value) as aum').joins(:security)
    data.map(&:aum).first
  end

  def value
    quantity * security.value
  end
end

app/models/security.rb
# == Schema Information
#
# Table name: securities
#
#  id         :bigint           not null, primary key
#  symbol     :string
#  buy_cost   :decimal(, )
#  sell_cost  :decimal(, )
#  value      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Security < ApplicationRecord
  include PgSearch::Model

  has_many :positions
  has_many :asset_class_securities

  multisearchable against: :symbol
  pg_search_scope :search_by_symbol, against: :symbol
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/securities_helper.rb
module SecuritiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simply Wealthy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item has-text-black has-text-weight-bold is-family-code" href="/">
          SIMPLY WEALTHY
        </a>
      </div>

      <div class="navbar-start">
        <%= link_to 'Dashboard', root_path, class: 'navbar-item' %>
        <%= link_to 'Clients', clients_path, class: 'navbar-item' %>
        <%= link_to 'Orders', orders_path, class: 'navbar-item' %>
        <%= link_to 'Activity', activities_path, class: 'navbar-item' %>
        <%= link_to 'Portfolios', portfolios_path, class: 'navbar-item' %>
        <%= link_to 'Securities', securities_path, class: 'navbar-item' %>
      </div>

      <div class="navbar-end">
        <div class="buttons" data-controller="modal-toggle">
          <button class="button is-primary" data-action="modal-toggle#show">Search</button>
          <div class="modal" data-modal-toggle-target="modal">
            <div class="modal-background"></div>
            <div id="site-search-card" class="modal-card" data-turbo-permanent>
              <header class="modal-card-head">
                <p class="modal-card-title">Search Everything</p>
                <button class="delete" aria-label="close" data-action="modal-toggle#hide"></button>
              </header>
              <%= form_tag search_results_path, method: :get, data: { turbo_frame: 'search-results', controller: 'auto-submit' } do %>
                <section class="modal-card-body">
                  <div class="field is-fullwidth">
                    <div class="control">
                      <%= text_field_tag 'q', nil, class: 'input', placeholder: 'Find a client, account, portfolio, security, etc.', data: { action: 'keyup->auto-submit#submit' } %>
                    </div>
                  </div>
                  <div>
                    <%= turbo_frame_tag 'search-results' %>
                  </div>
                </section>
                <footer class="modal-card-foot">
                </footer>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>